[2025-07-01T23:16:13.650+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-01T23:16:13.687+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_trino_silver_pipeline.dbt_test_silver scheduled__2025-07-01T23:14:00+00:00 [queued]>
[2025-07-01T23:16:13.699+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_trino_silver_pipeline.dbt_test_silver scheduled__2025-07-01T23:14:00+00:00 [queued]>
[2025-07-01T23:16:13.699+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-01T23:16:13.717+0000] {taskinstance.py:2330} INFO - Executing <Task(DockerOperator): dbt_test_silver> on 2025-07-01 23:14:00+00:00
[2025-07-01T23:16:13.726+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=861) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-01T23:16:13.727+0000] {standard_task_runner.py:64} INFO - Started process 862 to run task
[2025-07-01T23:16:13.726+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_trino_silver_pipeline', 'dbt_test_silver', 'scheduled__2025-07-01T23:14:00+00:00', '--job-id', '88', '--raw', '--subdir', 'DAGS_FOLDER/dbt_trino_silver_dag.py', '--cfg-path', '/tmp/tmpjmbp_ezn']
[2025-07-01T23:16:13.729+0000] {standard_task_runner.py:91} INFO - Job 88: Subtask dbt_test_silver
[2025-07-01T23:16:13.786+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_trino_silver_pipeline.dbt_test_silver scheduled__2025-07-01T23:14:00+00:00 [running]> on host 0a4aae371d36
[2025-07-01T23:16:13.893+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='admin@example.com' AIRFLOW_CTX_DAG_OWNER='data-team' AIRFLOW_CTX_DAG_ID='dbt_trino_silver_pipeline' AIRFLOW_CTX_TASK_ID='dbt_test_silver' AIRFLOW_CTX_EXECUTION_DATE='2025-07-01T23:14:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-01T23:14:00+00:00'
[2025-07-01T23:16:13.895+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-01T23:16:13.936+0000] {docker.py:367} INFO - Starting docker container from image modern-data-pipeline-dbt-trino:latest
[2025-07-01T23:16:14.226+0000] {docker.py:438} INFO - === Executando testes dbt ===
[2025-07-01T23:16:18.019+0000] {docker.py:438} INFO - [0m23:16:18  Running with dbt=1.7.0
[2025-07-01T23:16:18.582+0000] {docker.py:438} INFO - [0m23:16:18  Registered adapter: trino=1.7.0
[2025-07-01T23:16:18.633+0000] {docker.py:438} INFO - [0m23:16:18  Unable to do partial parsing because config vars, config profile, or config target have changed
[2025-07-01T23:16:20.835+0000] {docker.py:438} INFO - [0m23:16:20  Iniciando execu√ß√£o do dbt com Trino/Iceberg
[2025-07-01T23:16:20.868+0000] {docker.py:438} INFO - [0m23:16:20  Execu√ß√£o finalizada
[2025-07-01T23:16:21.474+0000] {docker.py:438} INFO - [0m23:16:21  Found 1 model, 29 tests, 5 operations, 1 source, 0 exposures, 0 metrics, 541 macros, 0 groups, 0 semantic models
[2025-07-01T23:16:21.478+0000] {docker.py:438} INFO - [0m23:16:21
[2025-07-01T23:16:21.706+0000] {docker.py:438} INFO - [0m23:16:21
[2025-07-01T23:16:21.708+0000] {docker.py:438} INFO - [0m23:16:21  Running 4 on-run-start hooks
[2025-07-01T23:16:21.712+0000] {docker.py:438} INFO - [0m23:16:21  Iniciando execu√ß√£o do dbt com Trino/Iceberg
[2025-07-01T23:16:21.718+0000] {docker.py:438} INFO - [0m23:16:21  1 of 4 START hook: agronegocio_iceberg.on-run-start.0 .......................... [RUN]
[2025-07-01T23:16:21.718+0000] {docker.py:438} INFO - [0m23:16:21  1 of 4 OK hook: agronegocio_iceberg.on-run-start.0 ............................. [[32mOK[0m in 0.00s]
[2025-07-01T23:16:21.745+0000] {docker.py:438} INFO - [0m23:16:21  Schema bronze criado/verificado
[2025-07-01T23:16:21.747+0000] {docker.py:438} INFO - [0m23:16:21  2 of 4 START hook: agronegocio_iceberg.on-run-start.1 .......................... [RUN]
[2025-07-01T23:16:21.748+0000] {docker.py:438} INFO - [0m23:16:21  2 of 4 OK hook: agronegocio_iceberg.on-run-start.1 ............................. [[32mOK[0m in 0.00s]
[2025-07-01T23:16:21.768+0000] {docker.py:438} INFO - [0m23:16:21  Schema silver criado/verificado
[2025-07-01T23:16:21.769+0000] {docker.py:438} INFO - [0m23:16:21  3 of 4 START hook: agronegocio_iceberg.on-run-start.2 .......................... [RUN]
[2025-07-01T23:16:21.770+0000] {docker.py:438} INFO - [0m23:16:21  3 of 4 OK hook: agronegocio_iceberg.on-run-start.2 ............................. [[32mOK[0m in 0.00s]
[2025-07-01T23:16:21.792+0000] {docker.py:438} INFO - [0m23:16:21  Schema gold criado/verificado
[2025-07-01T23:16:21.795+0000] {docker.py:438} INFO - [0m23:16:21  4 of 4 START hook: agronegocio_iceberg.on-run-start.3 .......................... [RUN]
[2025-07-01T23:16:21.795+0000] {docker.py:438} INFO - [0m23:16:21  4 of 4 OK hook: agronegocio_iceberg.on-run-start.3 ............................. [[32mOK[0m in 0.00s]
[2025-07-01T23:16:21.796+0000] {docker.py:438} INFO - [0m23:16:21
[2025-07-01T23:16:21.798+0000] {docker.py:438} INFO - [0m23:16:21  Concurrency: 2 threads (target='dev')
[2025-07-01T23:16:21.799+0000] {docker.py:438} INFO - [0m23:16:21
[2025-07-01T23:16:21.809+0000] {docker.py:438} INFO - [0m23:16:21  1 of 29 START test accepted_values_silver_dados_produtores_agro_trino_classificacao_propriedade__MINIFUNDIO__PEQUENA__MEDIA__GRANDE  [RUN]
[2025-07-01T23:16:21.810+0000] {docker.py:438} INFO - [0m23:16:21  2 of 29 START test accepted_values_silver_dados_produtores_agro_trino_cultura_principal__SOJA__MILHO__CAFE__CANA_DE_ACUCAR__ALGODAO__FRUTICULTURA__TRIGO__ARROZ__FEIJAO__EUCALIPTO  [RUN]
[2025-07-01T23:16:21.932+0000] {docker.py:438} INFO - [0m23:16:21  1 of 29 ERROR accepted_values_silver_dados_produtores_agro_trino_classificacao_propriedade__MINIFUNDIO__PEQUENA__MEDIA__GRANDE  [[31mERROR[0m in 0.12s]
[2025-07-01T23:16:21.935+0000] {docker.py:438} INFO - [0m23:16:21  3 of 29 START test accepted_values_silver_dados_produtores_agro_trino_faixa_risco_credito__SEM_SCORE__MUITO_ALTO__ALTO__MEDIO__BAIXO  [RUN]
[2025-07-01T23:16:22.031+0000] {docker.py:438} INFO - [0m23:16:22  3 of 29 ERROR accepted_values_silver_dados_produtores_agro_trino_faixa_risco_credito__SEM_SCORE__MUITO_ALTO__ALTO__MEDIO__BAIXO  [[31mERROR[0m in 0.09s]
[2025-07-01T23:16:22.038+0000] {docker.py:438} INFO - [0m23:16:22  4 of 29 START test accepted_values_silver_dados_produtores_agro_trino_finalidade_credito__CUSTEIO_SAFRA__INVESTIMENTO_MAQUINARIO__AMPLIACAO_AREA__OUTROS  [RUN]
[2025-07-01T23:16:22.420+0000] {docker.py:438} INFO - [0m23:16:22  2 of 29 PASS accepted_values_silver_dados_produtores_agro_trino_cultura_principal__SOJA__MILHO__CAFE__CANA_DE_ACUCAR__ALGODAO__FRUTICULTURA__TRIGO__ARROZ__FEIJAO__EUCALIPTO  [[32mPASS[0m in 0.61s]
[2025-07-01T23:16:22.426+0000] {docker.py:438} INFO - [0m23:16:22  5 of 29 START test accepted_values_silver_dados_produtores_agro_trino_registro_valido__True  [RUN]
[2025-07-01T23:16:22.553+0000] {docker.py:438} INFO - [0m23:16:22  5 of 29 ERROR accepted_values_silver_dados_produtores_agro_trino_registro_valido__True  [[31mERROR[0m in 0.13s]
[2025-07-01T23:16:22.561+0000] {docker.py:438} INFO - [0m23:16:22  6 of 29 START test accepted_values_silver_dados_produtores_agro_trino_tipo_pessoa__FISICA__JURIDICA  [RUN]
[2025-07-01T23:16:22.638+0000] {docker.py:438} INFO - [0m23:16:22  4 of 29 PASS accepted_values_silver_dados_produtores_agro_trino_finalidade_credito__CUSTEIO_SAFRA__INVESTIMENTO_MAQUINARIO__AMPLIACAO_AREA__OUTROS  [[32mPASS[0m in 0.60s]
[2025-07-01T23:16:22.644+0000] {docker.py:438} INFO - [0m23:16:22  7 of 29 START test dbt_utils_expression_is_true_silver_dados_produtores_agro_trino_area_total_hectares___0  [RUN]
[2025-07-01T23:16:23.332+0000] {docker.py:438} INFO - [0m23:16:23  6 of 29 PASS accepted_values_silver_dados_produtores_agro_trino_tipo_pessoa__FISICA__JURIDICA  [[32mPASS[0m in 0.77s]
[2025-07-01T23:16:23.337+0000] {docker.py:438} INFO - [0m23:16:23  8 of 29 START test dbt_utils_expression_is_true_silver_dados_produtores_agro_trino_localizacao_latitude__BETWEEN_90_AND_90  [RUN]
[2025-07-01T23:16:23.415+0000] {docker.py:438} INFO - [0m23:16:23  7 of 29 PASS dbt_utils_expression_is_true_silver_dados_produtores_agro_trino_area_total_hectares___0  [[32mPASS[0m in 0.77s]
[2025-07-01T23:16:23.431+0000] {docker.py:438} INFO - [0m23:16:23  9 of 29 START test dbt_utils_expression_is_true_silver_dados_produtores_agro_trino_localizacao_longitude__BETWEEN_180_AND_180  [RUN]
[2025-07-01T23:16:23.554+0000] {docker.py:438} INFO - [0m23:16:23  8 of 29 ERROR dbt_utils_expression_is_true_silver_dados_produtores_agro_trino_localizacao_latitude__BETWEEN_90_AND_90  [[31mERROR[0m in 0.20s]
[2025-07-01T23:16:23.555+0000] {docker.py:438} INFO - [0m23:16:23  10 of 29 START test dbt_utils_expression_is_true_silver_dados_produtores_agro_trino_valor_solicitado_credito___0  [RUN]
[2025-07-01T23:16:23.614+0000] {docker.py:438} INFO - [0m23:16:23  9 of 29 ERROR dbt_utils_expression_is_true_silver_dados_produtores_agro_trino_localizacao_longitude__BETWEEN_180_AND_180  [[31mERROR[0m in 0.19s]
[2025-07-01T23:16:23.631+0000] {docker.py:438} INFO - [0m23:16:23  11 of 29 START test dbt_utils_recency_silver_dados_produtores_agro_trino_hour__processed_at__24  [RUN]
[2025-07-01T23:16:23.839+0000] {docker.py:438} INFO - [0m23:16:23  11 of 29 ERROR dbt_utils_recency_silver_dados_produtores_agro_trino_hour__processed_at__24  [[31mERROR[0m in 0.21s]
[2025-07-01T23:16:23.842+0000] {docker.py:438} INFO - [0m23:16:23  12 of 29 START test dbt_utils_unique_combination_of_columns_silver_dados_produtores_agro_trino_proponente_id__data_solicitacao  [RUN]
[2025-07-01T23:16:24.457+0000] {docker.py:438} INFO - [0m23:16:24  10 of 29 PASS dbt_utils_expression_is_true_silver_dados_produtores_agro_trino_valor_solicitado_credito___0  [[32mPASS[0m in 0.91s]
[2025-07-01T23:16:24.460+0000] {docker.py:438} INFO - [0m23:16:24  13 of 29 START test not_null_silver_dados_produtores_agro_trino_area_total_hectares  [RUN]
[2025-07-01T23:16:25.988+0000] {docker.py:438} INFO - [0m23:16:25  13 of 29 PASS not_null_silver_dados_produtores_agro_trino_area_total_hectares .. [[32mPASS[0m in 1.52s]
[2025-07-01T23:16:25.989+0000] {docker.py:438} INFO - [0m23:16:25  14 of 29 START test not_null_silver_dados_produtores_agro_trino_classificacao_propriedade  [RUN]
[2025-07-01T23:16:26.030+0000] {docker.py:438} INFO - [0m23:16:26  12 of 29 FAIL 2 dbt_utils_unique_combination_of_columns_silver_dados_produtores_agro_trino_proponente_id__data_solicitacao  [[31mFAIL 2[0m in 2.19s]
[2025-07-01T23:16:26.035+0000] {docker.py:438} INFO - [0m23:16:26  15 of 29 START test not_null_silver_dados_produtores_agro_trino_cpf_cnpj ....... [RUN]
[2025-07-01T23:16:26.089+0000] {docker.py:438} INFO - [0m23:16:26  14 of 29 ERROR not_null_silver_dados_produtores_agro_trino_classificacao_propriedade  [[31mERROR[0m in 0.10s]
[2025-07-01T23:16:26.096+0000] {docker.py:438} INFO - [0m23:16:26  16 of 29 START test not_null_silver_dados_produtores_agro_trino_cultura_principal  [RUN]
[2025-07-01T23:16:26.558+0000] {docker.py:438} INFO - [0m23:16:26  15 of 29 PASS not_null_silver_dados_produtores_agro_trino_cpf_cnpj ............. [[32mPASS[0m in 0.52s]
[2025-07-01T23:16:26.561+0000] {docker.py:438} INFO - [0m23:16:26  17 of 29 START test not_null_silver_dados_produtores_agro_trino_data_solicitacao  [RUN]
[2025-07-01T23:16:26.732+0000] {docker.py:438} INFO - [0m23:16:26  16 of 29 PASS not_null_silver_dados_produtores_agro_trino_cultura_principal .... [[32mPASS[0m in 0.63s]
[2025-07-01T23:16:26.738+0000] {docker.py:438} INFO - [0m23:16:26  18 of 29 START test not_null_silver_dados_produtores_agro_trino_faixa_risco_credito  [RUN]
[2025-07-01T23:16:26.820+0000] {docker.py:438} INFO - [0m23:16:26  18 of 29 ERROR not_null_silver_dados_produtores_agro_trino_faixa_risco_credito . [[31mERROR[0m in 0.08s]
[2025-07-01T23:16:26.824+0000] {docker.py:438} INFO - [0m23:16:26  19 of 29 START test not_null_silver_dados_produtores_agro_trino_finalidade_credito  [RUN]
[2025-07-01T23:16:27.094+0000] {docker.py:438} INFO - [0m23:16:27  17 of 29 PASS not_null_silver_dados_produtores_agro_trino_data_solicitacao ..... [[32mPASS[0m in 0.53s]
[2025-07-01T23:16:27.097+0000] {docker.py:438} INFO - [0m23:16:27  20 of 29 START test not_null_silver_dados_produtores_agro_trino_localizacao_uf . [RUN]
[2025-07-01T23:16:27.181+0000] {docker.py:438} INFO - [0m23:16:27  20 of 29 ERROR not_null_silver_dados_produtores_agro_trino_localizacao_uf ...... [[31mERROR[0m in 0.08s]
[2025-07-01T23:16:27.184+0000] {docker.py:438} INFO - [0m23:16:27  21 of 29 START test not_null_silver_dados_produtores_agro_trino_processed_at ... [RUN]
[2025-07-01T23:16:27.277+0000] {docker.py:438} INFO - [0m23:16:27  21 of 29 ERROR not_null_silver_dados_produtores_agro_trino_processed_at ........ [[31mERROR[0m in 0.09s]
[2025-07-01T23:16:27.283+0000] {docker.py:438} INFO - [0m23:16:27  22 of 29 START test not_null_silver_dados_produtores_agro_trino_proponente_id .. [RUN]
[2025-07-01T23:16:27.385+0000] {docker.py:438} INFO - [0m23:16:27  19 of 29 PASS not_null_silver_dados_produtores_agro_trino_finalidade_credito ... [[32mPASS[0m in 0.56s]
[2025-07-01T23:16:27.396+0000] {docker.py:438} INFO - [0m23:16:27  23 of 29 START test not_null_silver_dados_produtores_agro_trino_registro_valido  [RUN]
[2025-07-01T23:16:27.490+0000] {docker.py:438} INFO - [0m23:16:27  23 of 29 ERROR not_null_silver_dados_produtores_agro_trino_registro_valido ..... [[31mERROR[0m in 0.09s]
[2025-07-01T23:16:27.494+0000] {docker.py:438} INFO - [0m23:16:27  24 of 29 START test not_null_silver_dados_produtores_agro_trino_row_hash ....... [RUN]
[2025-07-01T23:16:27.597+0000] {docker.py:438} INFO - [0m23:16:27  24 of 29 ERROR not_null_silver_dados_produtores_agro_trino_row_hash ............ [[31mERROR[0m in 0.10s]
[2025-07-01T23:16:27.602+0000] {docker.py:438} INFO - [0m23:16:27  25 of 29 START test not_null_silver_dados_produtores_agro_trino_tipo_pessoa .... [RUN]
[2025-07-01T23:16:27.905+0000] {docker.py:438} INFO - [0m23:16:27  22 of 29 PASS not_null_silver_dados_produtores_agro_trino_proponente_id ........ [[32mPASS[0m in 0.62s]
[2025-07-01T23:16:27.914+0000] {docker.py:438} INFO - [0m23:16:27  26 of 29 START test not_null_silver_dados_produtores_agro_trino_valor_solicitado_credito  [RUN]
[2025-07-01T23:16:28.265+0000] {docker.py:438} INFO - [0m23:16:28  25 of 29 PASS not_null_silver_dados_produtores_agro_trino_tipo_pessoa .......... [[32mPASS[0m in 0.66s]
[2025-07-01T23:16:28.270+0000] {docker.py:438} INFO - [0m23:16:28  27 of 29 START test source_not_null_bronze_dados_produtores_agro_proponente_id . [RUN]
[2025-07-01T23:16:28.472+0000] {docker.py:438} INFO - [0m23:16:28  26 of 29 PASS not_null_silver_dados_produtores_agro_trino_valor_solicitado_credito  [[32mPASS[0m in 0.56s]
[2025-07-01T23:16:28.476+0000] {docker.py:438} INFO - [0m23:16:28  28 of 29 START test test_incremental_integrity_trino ........................... [RUN]
[2025-07-01T23:16:28.562+0000] {docker.py:438} INFO - [0m23:16:28  28 of 29 ERROR test_incremental_integrity_trino ................................ [[31mERROR[0m in 0.09s]
[2025-07-01T23:16:28.566+0000] {docker.py:438} INFO - [0m23:16:28  29 of 29 START test unique_silver_dados_produtores_agro_trino_proponente_id .... [RUN]
[2025-07-01T23:16:28.776+0000] {docker.py:438} INFO - [0m23:16:28  27 of 29 PASS source_not_null_bronze_dados_produtores_agro_proponente_id ....... [[32mPASS[0m in 0.51s]
[2025-07-01T23:16:29.405+0000] {docker.py:438} INFO - [0m23:16:29  29 of 29 FAIL 2 unique_silver_dados_produtores_agro_trino_proponente_id ........ [[31mFAIL 2[0m in 0.83s]
[2025-07-01T23:16:29.411+0000] {docker.py:438} INFO - [0m23:16:29
[2025-07-01T23:16:29.411+0000] {docker.py:438} INFO - [0m23:16:29  Running 1 on-run-end hook
[2025-07-01T23:16:29.420+0000] {docker.py:438} INFO - [0m23:16:29  Execu√ß√£o finalizada
[2025-07-01T23:16:29.421+0000] {docker.py:438} INFO - [0m23:16:29  1 of 1 START hook: agronegocio_iceberg.on-run-end.0 ............................ [RUN]
[2025-07-01T23:16:29.422+0000] {docker.py:438} INFO - [0m23:16:29  1 of 1 OK hook: agronegocio_iceberg.on-run-end.0 ............................... [[32mOK[0m in 0.00s]
[2025-07-01T23:16:29.423+0000] {docker.py:438} INFO - [0m23:16:29
[2025-07-01T23:16:29.426+0000] {docker.py:438} INFO - [0m23:16:29
[2025-07-01T23:16:29.426+0000] {docker.py:438} INFO - [0m23:16:29  Finished running 29 tests, 5 hooks in 0 hours 0 minutes and 7.95 seconds (7.95s).
[2025-07-01T23:16:29.459+0000] {docker.py:438} INFO - [0m23:16:29
[2025-07-01T23:16:29.460+0000] {docker.py:438} INFO - [0m23:16:29  [31mCompleted with 15 errors and 0 warnings:[0m
[2025-07-01T23:16:29.461+0000] {docker.py:438} INFO - [0m23:16:29
[2025-07-01T23:16:29.462+0000] {docker.py:438} INFO - [0m23:16:29    Database Error in test accepted_values_silver_dados_produtores_agro_trino_classificacao_propriedade__MINIFUNDIO__PEQUENA__MEDIA__GRANDE (models/silver/schema.yml)
[2025-07-01T23:16:29.462+0000] {docker.py:438} INFO -   TrinoUserError(type=USER_ERROR, name=COLUMN_NOT_FOUND, message="line 18:9: Column 'classificacao_propriedade' cannot be resolved", query_id=20250701_231621_00500_ivifs)
[2025-07-01T23:16:29.463+0000] {docker.py:438} INFO - [0m23:16:29
[2025-07-01T23:16:29.463+0000] {docker.py:438} INFO - [0m23:16:29    Database Error in test accepted_values_silver_dados_produtores_agro_trino_faixa_risco_credito__SEM_SCORE__MUITO_ALTO__ALTO__MEDIO__BAIXO (models/silver/schema.yml)
[2025-07-01T23:16:29.464+0000] {docker.py:438} INFO -   TrinoUserError(type=USER_ERROR, name=COLUMN_NOT_FOUND, message="line 18:9: Column 'faixa_risco_credito' cannot be resolved", query_id=20250701_231621_00502_ivifs)
[2025-07-01T23:16:29.464+0000] {docker.py:438} INFO - [0m23:16:29
[2025-07-01T23:16:29.465+0000] {docker.py:438} INFO - [0m23:16:29    Database Error in test accepted_values_silver_dados_produtores_agro_trino_registro_valido__True (models/silver/schema.yml)
[2025-07-01T23:16:29.465+0000] {docker.py:438} INFO -   TrinoUserError(type=USER_ERROR, name=COLUMN_NOT_FOUND, message="line 18:9: Column 'registro_valido' cannot be resolved", query_id=20250701_231622_00507_ivifs)
[2025-07-01T23:16:29.466+0000] {docker.py:438} INFO - [0m23:16:29
[2025-07-01T23:16:29.466+0000] {docker.py:438} INFO - [0m23:16:29    Database Error in test dbt_utils_expression_is_true_silver_dados_produtores_agro_trino_localizacao_latitude__BETWEEN_90_AND_90 (models/silver/schema.yml)
[2025-07-01T23:16:29.466+0000] {docker.py:438} INFO -   TrinoUserError(type=USER_ERROR, name=COLUMN_NOT_FOUND, message="line 17:83: Column 'localizacao_latitude' cannot be resolved", query_id=20250701_231623_00515_ivifs)
[2025-07-01T23:16:29.467+0000] {docker.py:438} INFO - [0m23:16:29
[2025-07-01T23:16:29.468+0000] {docker.py:438} INFO - [0m23:16:29    Database Error in test dbt_utils_expression_is_true_silver_dados_produtores_agro_trino_localizacao_longitude__BETWEEN_180_AND_180 (models/silver/schema.yml)
[2025-07-01T23:16:29.468+0000] {docker.py:438} INFO -   TrinoUserError(type=USER_ERROR, name=COLUMN_NOT_FOUND, message="line 17:83: Column 'localizacao_longitude' cannot be resolved", query_id=20250701_231623_00516_ivifs)
[2025-07-01T23:16:29.469+0000] {docker.py:438} INFO - [0m23:16:29
[2025-07-01T23:16:29.469+0000] {docker.py:438} INFO - [0m23:16:29    Database Error in test dbt_utils_recency_silver_dados_produtores_agro_trino_hour__processed_at__24 (models/silver/schema.yml)
[2025-07-01T23:16:29.469+0000] {docker.py:438} INFO -   TrinoUserError(type=USER_ERROR, name=COLUMN_NOT_FOUND, message="line 24:13: Column 'processed_at' cannot be resolved", query_id=20250701_231623_00518_ivifs)
[2025-07-01T23:16:29.470+0000] {docker.py:438} INFO - [0m23:16:29
[2025-07-01T23:16:29.471+0000] {docker.py:438} INFO - [0m23:16:29  [31mFailure in test dbt_utils_unique_combination_of_columns_silver_dados_produtores_agro_trino_proponente_id__data_solicitacao (models/silver/schema.yml)[0m
[2025-07-01T23:16:29.473+0000] {docker.py:438} INFO - [0m23:16:29    Got 2 results, configured to fail if != 0
[2025-07-01T23:16:29.473+0000] {docker.py:438} INFO - [0m23:16:29
[2025-07-01T23:16:29.474+0000] {docker.py:438} INFO - [0m23:16:29    compiled Code at target/compiled/agronegocio_iceberg/models/silver/schema.yml/dbt_utils_unique_combination_o_21ab17eecd767bb91bd0b03d651fdd82.sql
[2025-07-01T23:16:29.474+0000] {docker.py:438} INFO - [0m23:16:29
[2025-07-01T23:16:29.475+0000] {docker.py:438} INFO - [0m23:16:29    See test failures:
[2025-07-01T23:16:29.475+0000] {docker.py:438} INFO -   ------------------------------------------------------------------------------------------------------------------
[2025-07-01T23:16:29.475+0000] {docker.py:438} INFO -   select * from "iceberg"."silver_dbt_test__audit"."dbt_utils_unique_combination_o_21ab17eecd767bb91bd0b03d651fdd82"
[2025-07-01T23:16:29.476+0000] {docker.py:438} INFO -   ------------------------------------------------------------------------------------------------------------------
[2025-07-01T23:16:29.476+0000] {docker.py:438} INFO - [0m23:16:29
[2025-07-01T23:16:29.476+0000] {docker.py:438} INFO - [0m23:16:29    Database Error in test not_null_silver_dados_produtores_agro_trino_classificacao_propriedade (models/silver/schema.yml)
[2025-07-01T23:16:29.477+0000] {docker.py:438} INFO -   TrinoUserError(type=USER_ERROR, name=COLUMN_NOT_FOUND, message="line 19:7: Column 'classificacao_propriedade' cannot be resolved", query_id=20250701_231626_00527_ivifs)
[2025-07-01T23:16:29.477+0000] {docker.py:438} INFO - [0m23:16:29
[2025-07-01T23:16:29.477+0000] {docker.py:438} INFO - [0m23:16:29    Database Error in test not_null_silver_dados_produtores_agro_trino_faixa_risco_credito (models/silver/schema.yml)
[2025-07-01T23:16:29.478+0000] {docker.py:438} INFO -   TrinoUserError(type=USER_ERROR, name=COLUMN_NOT_FOUND, message="line 19:7: Column 'faixa_risco_credito' cannot be resolved", query_id=20250701_231626_00536_ivifs)
[2025-07-01T23:16:29.483+0000] {docker.py:438} INFO - [0m23:16:29
[2025-07-01T23:16:29.484+0000] {docker.py:438} INFO - [0m23:16:29    Database Error in test not_null_silver_dados_produtores_agro_trino_localizacao_uf (models/silver/schema.yml)
[2025-07-01T23:16:29.484+0000] {docker.py:438} INFO -   TrinoUserError(type=USER_ERROR, name=COLUMN_NOT_FOUND, message="line 19:7: Column 'localizacao_uf' cannot be resolved", query_id=20250701_231627_00540_ivifs)
[2025-07-01T23:16:29.484+0000] {docker.py:438} INFO - [0m23:16:29
[2025-07-01T23:16:29.485+0000] {docker.py:438} INFO - [0m23:16:29    Database Error in test not_null_silver_dados_produtores_agro_trino_processed_at (models/silver/schema.yml)
[2025-07-01T23:16:29.485+0000] {docker.py:438} INFO -   TrinoUserError(type=USER_ERROR, name=COLUMN_NOT_FOUND, message="line 19:7: Column 'processed_at' cannot be resolved", query_id=20250701_231627_00541_ivifs)
[2025-07-01T23:16:29.485+0000] {docker.py:438} INFO - [0m23:16:29
[2025-07-01T23:16:29.486+0000] {docker.py:438} INFO - [0m23:16:29    Database Error in test not_null_silver_dados_produtores_agro_trino_registro_valido (models/silver/schema.yml)
[2025-07-01T23:16:29.486+0000] {docker.py:438} INFO -   TrinoUserError(type=USER_ERROR, name=COLUMN_NOT_FOUND, message="line 19:7: Column 'registro_valido' cannot be resolved", query_id=20250701_231627_00544_ivifs)
[2025-07-01T23:16:29.486+0000] {docker.py:438} INFO - [0m23:16:29
[2025-07-01T23:16:29.487+0000] {docker.py:438} INFO - [0m23:16:29    Database Error in test not_null_silver_dados_produtores_agro_trino_row_hash (models/silver/schema.yml)
[2025-07-01T23:16:29.490+0000] {docker.py:438} INFO -   TrinoUserError(type=USER_ERROR, name=COLUMN_NOT_FOUND, message="line 19:7: Column 'row_hash' cannot be resolved", query_id=20250701_231627_00546_ivifs)
[2025-07-01T23:16:29.490+0000] {docker.py:438} INFO - [0m23:16:29
[2025-07-01T23:16:29.490+0000] {docker.py:438} INFO - [0m23:16:29    Database Error in test test_incremental_integrity_trino (tests/singular/test_incremental_integrity_trino.sql)
[2025-07-01T23:16:29.491+0000] {docker.py:438} INFO -   TrinoUserError(type=USER_ERROR, name=COLUMN_NOT_FOUND, message="line 22:11: Column 'processed_at' cannot be resolved", query_id=20250701_231628_00556_ivifs)
[2025-07-01T23:16:29.491+0000] {docker.py:438} INFO - [0m23:16:29
[2025-07-01T23:16:29.492+0000] {docker.py:438} INFO - [0m23:16:29  [31mFailure in test unique_silver_dados_produtores_agro_trino_proponente_id (models/silver/schema.yml)[0m
[2025-07-01T23:16:29.492+0000] {docker.py:438} INFO - [0m23:16:29    Got 2 results, configured to fail if != 0
[2025-07-01T23:16:29.492+0000] {docker.py:438} INFO - [0m23:16:29
[2025-07-01T23:16:29.493+0000] {docker.py:438} INFO - [0m23:16:29    compiled Code at target/compiled/agronegocio_iceberg/models/silver/schema.yml/unique_silver_dados_produtores_agro_trino_proponente_id.sql
[2025-07-01T23:16:29.493+0000] {docker.py:438} INFO - [0m23:16:29
[2025-07-01T23:16:29.493+0000] {docker.py:438} INFO - [0m23:16:29    See test failures:
[2025-07-01T23:16:29.494+0000] {docker.py:438} INFO -   ----------------------------------------------------------------------------------------------------------
[2025-07-01T23:16:29.494+0000] {docker.py:438} INFO -   select * from "iceberg"."silver_dbt_test__audit"."unique_silver_dados_produtores_agro_trino_proponente_id"
[2025-07-01T23:16:29.494+0000] {docker.py:438} INFO -   ----------------------------------------------------------------------------------------------------------
[2025-07-01T23:16:29.494+0000] {docker.py:438} INFO - [0m23:16:29
[2025-07-01T23:16:29.495+0000] {docker.py:438} INFO - [0m23:16:29  Done. PASS=14 WARN=0 ERROR=15 SKIP=0 TOTAL=29
[2025-07-01T23:16:30.652+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-01T23:16:30.660+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 460, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 513, in execute
    return self._run_image()
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 384, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 446, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2025-07-01T23:16:30.665+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dbt_trino_silver_pipeline, task_id=dbt_test_silver, run_id=scheduled__2025-07-01T23:14:00+00:00, execution_date=20250701T231400, start_date=20250701T231613, end_date=20250701T231630
[2025-07-01T23:16:30.679+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 88 for task dbt_test_silver (Docker container failed: {'StatusCode': 1}; 862)
[2025-07-01T23:16:30.707+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-07-01T23:16:30.764+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-01T23:16:30.773+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
