[2025-07-01T23:00:02.024+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-01T23:00:02.070+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_trino_silver_pipeline.dbt_run_silver scheduled__2025-07-01T22:58:00+00:00 [queued]>
[2025-07-01T23:00:02.081+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_trino_silver_pipeline.dbt_run_silver scheduled__2025-07-01T22:58:00+00:00 [queued]>
[2025-07-01T23:00:02.081+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-01T23:00:02.097+0000] {taskinstance.py:2330} INFO - Executing <Task(DockerOperator): dbt_run_silver> on 2025-07-01 22:58:00+00:00
[2025-07-01T23:00:02.105+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=532) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-01T23:00:02.106+0000] {standard_task_runner.py:64} INFO - Started process 533 to run task
[2025-07-01T23:00:02.105+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_trino_silver_pipeline', 'dbt_run_silver', 'scheduled__2025-07-01T22:58:00+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/dbt_trino_silver_dag.py', '--cfg-path', '/tmp/tmpybawymh8']
[2025-07-01T23:00:02.108+0000] {standard_task_runner.py:91} INFO - Job 65: Subtask dbt_run_silver
[2025-07-01T23:00:02.160+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_trino_silver_pipeline.dbt_run_silver scheduled__2025-07-01T22:58:00+00:00 [running]> on host 0a4aae371d36
[2025-07-01T23:00:02.273+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='admin@example.com' AIRFLOW_CTX_DAG_OWNER='data-team' AIRFLOW_CTX_DAG_ID='dbt_trino_silver_pipeline' AIRFLOW_CTX_TASK_ID='dbt_run_silver' AIRFLOW_CTX_EXECUTION_DATE='2025-07-01T22:58:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-01T22:58:00+00:00'
[2025-07-01T23:00:02.274+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-01T23:00:02.323+0000] {docker.py:367} INFO - Starting docker container from image modern-data-pipeline-dbt-trino:latest
[2025-07-01T23:00:02.600+0000] {docker.py:438} INFO - === Executando dbt run incremental ===
[2025-07-01T23:00:05.840+0000] {docker.py:438} INFO - [0m23:00:05  Running with dbt=1.7.0
[2025-07-01T23:00:06.352+0000] {docker.py:438} INFO - [0m23:00:06  Registered adapter: trino=1.7.0
[2025-07-01T23:00:06.391+0000] {docker.py:438} INFO - [0m23:00:06  Unable to do partial parsing because a project config has changed
[2025-07-01T23:00:08.400+0000] {docker.py:438} INFO - [0m23:00:08  Iniciando execu√ß√£o do dbt com Trino/Iceberg
[2025-07-01T23:00:08.436+0000] {docker.py:438} INFO - [0m23:00:08  Execu√ß√£o finalizada
[2025-07-01T23:00:09.093+0000] {docker.py:438} INFO - [0m23:00:09  Found 1 model, 29 tests, 5 operations, 1 source, 0 exposures, 0 metrics, 541 macros, 0 groups, 0 semantic models
[2025-07-01T23:00:09.096+0000] {docker.py:438} INFO - [0m23:00:09
[2025-07-01T23:00:09.477+0000] {docker.py:438} INFO - [0m23:00:09
[2025-07-01T23:00:09.478+0000] {docker.py:438} INFO - [0m23:00:09  Running 4 on-run-start hooks
[2025-07-01T23:00:09.485+0000] {docker.py:438} INFO - [0m23:00:09  Iniciando execu√ß√£o do dbt com Trino/Iceberg
[2025-07-01T23:00:09.493+0000] {docker.py:438} INFO - [0m23:00:09  1 of 4 START hook: agronegocio_iceberg.on-run-start.0 .......................... [RUN]
[2025-07-01T23:00:09.493+0000] {docker.py:438} INFO - [0m23:00:09  1 of 4 OK hook: agronegocio_iceberg.on-run-start.0 ............................. [[32mOK[0m in 0.00s]
[2025-07-01T23:00:09.524+0000] {docker.py:438} INFO - [0m23:00:09  Schema bronze criado/verificado
[2025-07-01T23:00:09.526+0000] {docker.py:438} INFO - [0m23:00:09  2 of 4 START hook: agronegocio_iceberg.on-run-start.1 .......................... [RUN]
[2025-07-01T23:00:09.527+0000] {docker.py:438} INFO - [0m23:00:09  2 of 4 OK hook: agronegocio_iceberg.on-run-start.1 ............................. [[32mOK[0m in 0.00s]
[2025-07-01T23:00:09.559+0000] {docker.py:438} INFO - [0m23:00:09  Schema silver criado/verificado
[2025-07-01T23:00:09.561+0000] {docker.py:438} INFO - [0m23:00:09  3 of 4 START hook: agronegocio_iceberg.on-run-start.2 .......................... [RUN]
[2025-07-01T23:00:09.562+0000] {docker.py:438} INFO - [0m23:00:09  3 of 4 OK hook: agronegocio_iceberg.on-run-start.2 ............................. [[32mOK[0m in 0.00s]
[2025-07-01T23:00:09.593+0000] {docker.py:438} INFO - [0m23:00:09  Schema gold criado/verificado
[2025-07-01T23:00:09.595+0000] {docker.py:438} INFO - [0m23:00:09  4 of 4 START hook: agronegocio_iceberg.on-run-start.3 .......................... [RUN]
[2025-07-01T23:00:09.596+0000] {docker.py:438} INFO - [0m23:00:09  4 of 4 OK hook: agronegocio_iceberg.on-run-start.3 ............................. [[32mOK[0m in 0.00s]
[2025-07-01T23:00:09.597+0000] {docker.py:438} INFO - [0m23:00:09
[2025-07-01T23:00:09.599+0000] {docker.py:438} INFO - [0m23:00:09  Concurrency: 2 threads (target='dev')
[2025-07-01T23:00:09.600+0000] {docker.py:438} INFO - [0m23:00:09
[2025-07-01T23:00:09.610+0000] {docker.py:438} INFO - [0m23:00:09  1 of 1 START sql incremental model silver.silver_dados_produtores_agro_trino ... [RUN]
[2025-07-01T23:00:09.781+0000] {docker.py:438} INFO - [0m23:00:09  1 of 1 ERROR creating sql incremental model silver.silver_dados_produtores_agro_trino  [[31mERROR[0m in 0.17s]
[2025-07-01T23:00:09.785+0000] {docker.py:438} INFO - [0m23:00:09
[2025-07-01T23:00:09.786+0000] {docker.py:438} INFO - [0m23:00:09  Running 1 on-run-end hook
[2025-07-01T23:00:09.792+0000] {docker.py:438} INFO - [0m23:00:09  Execu√ß√£o finalizada
[2025-07-01T23:00:09.794+0000] {docker.py:438} INFO - [0m23:00:09  1 of 1 START hook: agronegocio_iceberg.on-run-end.0 ............................ [RUN]
[2025-07-01T23:00:09.795+0000] {docker.py:438} INFO - [0m23:00:09  1 of 1 OK hook: agronegocio_iceberg.on-run-end.0 ............................... [[32mOK[0m in 0.00s]
[2025-07-01T23:00:09.795+0000] {docker.py:438} INFO - [0m23:00:09
[2025-07-01T23:00:09.798+0000] {docker.py:438} INFO - [0m23:00:09
[2025-07-01T23:00:09.799+0000] {docker.py:438} INFO - [0m23:00:09  Finished running 1 incremental model, 5 hooks in 0 hours 0 minutes and 0.70 seconds (0.70s).
[2025-07-01T23:00:09.816+0000] {docker.py:438} INFO - [0m23:00:09
[2025-07-01T23:00:09.817+0000] {docker.py:438} INFO - [0m23:00:09  [31mCompleted with 1 error and 0 warnings:[0m
[2025-07-01T23:00:09.817+0000] {docker.py:438} INFO - [0m23:00:09
[2025-07-01T23:00:09.818+0000] {docker.py:438} INFO - [0m23:00:09    Database Error in model silver_dados_produtores_agro_trino (models/silver/silver_dados_produtores_agro_trino.sql)
[2025-07-01T23:00:09.818+0000] {docker.py:438} INFO -   TrinoUserError(type=USER_ERROR, name=TYPE_MISMATCH, message="line 48:9: Cannot cast bigint to timestamp(3)", query_id=20250701_230009_00021_ivifs)
[2025-07-01T23:00:09.818+0000] {docker.py:438} INFO -   compiled Code at target/run/agronegocio_iceberg/models/silver/silver_dados_produtores_agro_trino.sql
[2025-07-01T23:00:09.818+0000] {docker.py:438} INFO - [0m23:00:09
[2025-07-01T23:00:09.819+0000] {docker.py:438} INFO - [0m23:00:09  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
[2025-07-01T23:00:11.000+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-01T23:00:11.016+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 460, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 513, in execute
    return self._run_image()
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 384, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 446, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2025-07-01T23:00:11.025+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dbt_trino_silver_pipeline, task_id=dbt_run_silver, run_id=scheduled__2025-07-01T22:58:00+00:00, execution_date=20250701T225800, start_date=20250701T230002, end_date=20250701T230011
[2025-07-01T23:00:11.046+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 65 for task dbt_run_silver (Docker container failed: {'StatusCode': 1}; 533)
[2025-07-01T23:00:11.063+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-07-01T23:00:11.115+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-01T23:00:11.123+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
