[2025-07-01T22:58:02.220+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-01T22:58:02.287+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_trino_silver_pipeline.dbt_run_silver scheduled__2025-07-01T22:56:00+00:00 [queued]>
[2025-07-01T22:58:02.313+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_trino_silver_pipeline.dbt_run_silver scheduled__2025-07-01T22:56:00+00:00 [queued]>
[2025-07-01T22:58:02.314+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-01T22:58:02.344+0000] {taskinstance.py:2330} INFO - Executing <Task(DockerOperator): dbt_run_silver> on 2025-07-01 22:56:00+00:00
[2025-07-01T22:58:02.358+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=492) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-01T22:58:02.359+0000] {standard_task_runner.py:64} INFO - Started process 493 to run task
[2025-07-01T22:58:02.364+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_trino_silver_pipeline', 'dbt_run_silver', 'scheduled__2025-07-01T22:56:00+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/dbt_trino_silver_dag.py', '--cfg-path', '/tmp/tmplom7vyy4']
[2025-07-01T22:58:02.367+0000] {standard_task_runner.py:91} INFO - Job 63: Subtask dbt_run_silver
[2025-07-01T22:58:02.445+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_trino_silver_pipeline.dbt_run_silver scheduled__2025-07-01T22:56:00+00:00 [running]> on host 0a4aae371d36
[2025-07-01T22:58:02.602+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='admin@example.com' AIRFLOW_CTX_DAG_OWNER='data-team' AIRFLOW_CTX_DAG_ID='dbt_trino_silver_pipeline' AIRFLOW_CTX_TASK_ID='dbt_run_silver' AIRFLOW_CTX_EXECUTION_DATE='2025-07-01T22:56:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-01T22:56:00+00:00'
[2025-07-01T22:58:02.607+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-01T22:58:02.680+0000] {docker.py:367} INFO - Starting docker container from image modern-data-pipeline-dbt-trino:latest
[2025-07-01T22:58:03.327+0000] {docker.py:438} INFO - === Executando dbt run incremental ===
[2025-07-01T22:58:08.927+0000] {docker.py:438} INFO - [0m22:58:08  Running with dbt=1.7.0
[2025-07-01T22:58:09.778+0000] {docker.py:438} INFO - [0m22:58:09  Registered adapter: trino=1.7.0
[2025-07-01T22:58:09.849+0000] {docker.py:438} INFO - [0m22:58:09  Unable to do partial parsing because a project config has changed
[2025-07-01T22:58:13.254+0000] {docker.py:438} INFO - [0m22:58:13  Iniciando execu√ß√£o do dbt com Trino/Iceberg
[2025-07-01T22:58:13.295+0000] {docker.py:438} INFO - [0m22:58:13  Execu√ß√£o finalizada
[2025-07-01T22:58:14.422+0000] {docker.py:438} INFO - [0m22:58:14  Found 1 model, 29 tests, 5 operations, 1 source, 0 exposures, 0 metrics, 541 macros, 0 groups, 0 semantic models
[2025-07-01T22:58:14.427+0000] {docker.py:438} INFO - [0m22:58:14
[2025-07-01T22:58:15.172+0000] {docker.py:438} INFO - [0m22:58:15
[2025-07-01T22:58:15.174+0000] {docker.py:438} INFO - [0m22:58:15  Running 4 on-run-start hooks
[2025-07-01T22:58:15.182+0000] {docker.py:438} INFO - [0m22:58:15  Iniciando execu√ß√£o do dbt com Trino/Iceberg
[2025-07-01T22:58:15.193+0000] {docker.py:438} INFO - [0m22:58:15  1 of 4 START hook: agronegocio_iceberg.on-run-start.0 .......................... [RUN]
[2025-07-01T22:58:15.194+0000] {docker.py:438} INFO - [0m22:58:15  1 of 4 OK hook: agronegocio_iceberg.on-run-start.0 ............................. [[32mOK[0m in 0.00s]
[2025-07-01T22:58:15.201+0000] {docker.py:438} INFO - [0m22:58:15  2 of 4 START hook: agronegocio_iceberg.on-run-start.1 .......................... [RUN]
[2025-07-01T22:58:15.239+0000] {docker.py:438} INFO - [0m22:58:15  2 of 4 OK hook: agronegocio_iceberg.on-run-start.1 ............................. [[32mSUCCESS[0m in 0.04s]
[2025-07-01T22:58:15.247+0000] {docker.py:438} INFO - [0m22:58:15  3 of 4 START hook: agronegocio_iceberg.on-run-start.2 .......................... [RUN]
[2025-07-01T22:58:15.283+0000] {docker.py:438} INFO - [0m22:58:15  3 of 4 OK hook: agronegocio_iceberg.on-run-start.2 ............................. [[32mSUCCESS[0m in 0.03s]
[2025-07-01T22:58:15.290+0000] {docker.py:438} INFO - [0m22:58:15  4 of 4 START hook: agronegocio_iceberg.on-run-start.3 .......................... [RUN]
[2025-07-01T22:58:15.366+0000] {docker.py:438} INFO - [0m22:58:15  4 of 4 OK hook: agronegocio_iceberg.on-run-start.3 ............................. [[32mSUCCESS[0m in 0.08s]
[2025-07-01T22:58:15.373+0000] {docker.py:438} INFO - [0m22:58:15
[2025-07-01T22:58:15.377+0000] {docker.py:438} INFO - [0m22:58:15  Concurrency: 2 threads (target='dev')
[2025-07-01T22:58:15.377+0000] {docker.py:438} INFO - [0m22:58:15
[2025-07-01T22:58:15.405+0000] {docker.py:438} INFO - [0m22:58:15  1 of 1 START sql incremental model silver.silver_dados_produtores_agro_trino ... [RUN]
[2025-07-01T22:58:17.674+0000] {docker.py:438} INFO - [0m22:58:17  1 of 1 ERROR creating sql incremental model silver.silver_dados_produtores_agro_trino  [[31mERROR[0m in 2.27s]
[2025-07-01T22:58:17.680+0000] {docker.py:438} INFO - [0m22:58:17
[2025-07-01T22:58:17.682+0000] {docker.py:438} INFO - [0m22:58:17  Running 1 on-run-end hook
[2025-07-01T22:58:17.691+0000] {docker.py:438} INFO - [0m22:58:17  Execu√ß√£o finalizada
[2025-07-01T22:58:17.693+0000] {docker.py:438} INFO - [0m22:58:17  1 of 1 START hook: agronegocio_iceberg.on-run-end.0 ............................ [RUN]
[2025-07-01T22:58:17.694+0000] {docker.py:438} INFO - [0m22:58:17  1 of 1 OK hook: agronegocio_iceberg.on-run-end.0 ............................... [[32mOK[0m in 0.00s]
[2025-07-01T22:58:17.695+0000] {docker.py:438} INFO - [0m22:58:17
[2025-07-01T22:58:17.699+0000] {docker.py:438} INFO - [0m22:58:17
[2025-07-01T22:58:17.699+0000] {docker.py:438} INFO - [0m22:58:17  Finished running 1 incremental model, 5 hooks in 0 hours 0 minutes and 3.27 seconds (3.27s).
[2025-07-01T22:58:17.727+0000] {docker.py:438} INFO - [0m22:58:17
[2025-07-01T22:58:17.728+0000] {docker.py:438} INFO - [0m22:58:17  [31mCompleted with 1 error and 0 warnings:[0m
[2025-07-01T22:58:17.729+0000] {docker.py:438} INFO - [0m22:58:17
[2025-07-01T22:58:17.729+0000] {docker.py:438} INFO - [0m22:58:17    Database Error in model silver_dados_produtores_agro_trino (models/silver/silver_dados_produtores_agro_trino.sql)
[2025-07-01T22:58:17.730+0000] {docker.py:438} INFO -   TrinoUserError(type=USER_ERROR, name=TYPE_MISMATCH, message="line 48:9: Cannot cast bigint to timestamp(3)", query_id=20250701_225815_00015_ivifs)
[2025-07-01T22:58:17.730+0000] {docker.py:438} INFO -   compiled Code at target/run/agronegocio_iceberg/models/silver/silver_dados_produtores_agro_trino.sql
[2025-07-01T22:58:17.731+0000] {docker.py:438} INFO - [0m22:58:17
[2025-07-01T22:58:17.731+0000] {docker.py:438} INFO - [0m22:58:17  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
[2025-07-01T22:58:18.886+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-01T22:58:18.899+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 460, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 513, in execute
    return self._run_image()
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 384, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 446, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2025-07-01T22:58:18.904+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dbt_trino_silver_pipeline, task_id=dbt_run_silver, run_id=scheduled__2025-07-01T22:56:00+00:00, execution_date=20250701T225600, start_date=20250701T225802, end_date=20250701T225818
[2025-07-01T22:58:18.919+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 63 for task dbt_run_silver (Docker container failed: {'StatusCode': 1}; 493)
[2025-07-01T22:58:18.935+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-07-01T22:58:18.959+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-01T22:58:18.964+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
