[2025-07-01T23:10:13.306+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-01T23:10:13.333+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_trino_silver_pipeline.dbt_test_silver scheduled__2025-07-01T23:08:00+00:00 [queued]>
[2025-07-01T23:10:13.342+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_trino_silver_pipeline.dbt_test_silver scheduled__2025-07-01T23:08:00+00:00 [queued]>
[2025-07-01T23:10:13.342+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-01T23:10:13.354+0000] {taskinstance.py:2330} INFO - Executing <Task(DockerOperator): dbt_test_silver> on 2025-07-01 23:08:00+00:00
[2025-07-01T23:10:13.360+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=733) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-01T23:10:13.360+0000] {standard_task_runner.py:64} INFO - Started process 734 to run task
[2025-07-01T23:10:13.360+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_trino_silver_pipeline', 'dbt_test_silver', 'scheduled__2025-07-01T23:08:00+00:00', '--job-id', '79', '--raw', '--subdir', 'DAGS_FOLDER/dbt_trino_silver_dag.py', '--cfg-path', '/tmp/tmp7irxr2ai']
[2025-07-01T23:10:13.361+0000] {standard_task_runner.py:91} INFO - Job 79: Subtask dbt_test_silver
[2025-07-01T23:10:13.404+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_trino_silver_pipeline.dbt_test_silver scheduled__2025-07-01T23:08:00+00:00 [running]> on host 0a4aae371d36
[2025-07-01T23:10:13.478+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='admin@example.com' AIRFLOW_CTX_DAG_OWNER='data-team' AIRFLOW_CTX_DAG_ID='dbt_trino_silver_pipeline' AIRFLOW_CTX_TASK_ID='dbt_test_silver' AIRFLOW_CTX_EXECUTION_DATE='2025-07-01T23:08:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-01T23:08:00+00:00'
[2025-07-01T23:10:13.479+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-01T23:10:13.519+0000] {docker.py:367} INFO - Starting docker container from image modern-data-pipeline-dbt-trino:latest
[2025-07-01T23:10:13.800+0000] {docker.py:438} INFO - === Executando testes dbt ===
[2025-07-01T23:10:16.740+0000] {docker.py:438} INFO - [0m23:10:16  Running with dbt=1.7.0
[2025-07-01T23:10:17.188+0000] {docker.py:438} INFO - [0m23:10:17  Registered adapter: trino=1.7.0
[2025-07-01T23:10:17.263+0000] {docker.py:438} INFO - [0m23:10:17  Unable to do partial parsing because config vars, config profile, or config target have changed
[2025-07-01T23:10:20.318+0000] {docker.py:438} INFO - [0m23:10:20  Iniciando execu√ß√£o do dbt com Trino/Iceberg
[2025-07-01T23:10:20.367+0000] {docker.py:438} INFO - [0m23:10:20  Execu√ß√£o finalizada
[2025-07-01T23:10:21.179+0000] {docker.py:438} INFO - [0m23:10:21  Found 1 model, 29 tests, 5 operations, 1 source, 0 exposures, 0 metrics, 541 macros, 0 groups, 0 semantic models
[2025-07-01T23:10:21.186+0000] {docker.py:438} INFO - [0m23:10:21
[2025-07-01T23:10:21.700+0000] {docker.py:438} INFO - [0m23:10:21
[2025-07-01T23:10:21.701+0000] {docker.py:438} INFO - [0m23:10:21  Running 4 on-run-start hooks
[2025-07-01T23:10:21.710+0000] {docker.py:438} INFO - [0m23:10:21  Iniciando execu√ß√£o do dbt com Trino/Iceberg
[2025-07-01T23:10:21.722+0000] {docker.py:438} INFO - [0m23:10:21  1 of 4 START hook: agronegocio_iceberg.on-run-start.0 .......................... [RUN]
[2025-07-01T23:10:21.723+0000] {docker.py:438} INFO - [0m23:10:21  1 of 4 OK hook: agronegocio_iceberg.on-run-start.0 ............................. [[32mOK[0m in 0.00s]
[2025-07-01T23:10:21.773+0000] {docker.py:438} INFO - [0m23:10:21  Schema bronze criado/verificado
[2025-07-01T23:10:21.776+0000] {docker.py:438} INFO - [0m23:10:21  2 of 4 START hook: agronegocio_iceberg.on-run-start.1 .......................... [RUN]
[2025-07-01T23:10:21.777+0000] {docker.py:438} INFO - [0m23:10:21  2 of 4 OK hook: agronegocio_iceberg.on-run-start.1 ............................. [[32mOK[0m in 0.00s]
[2025-07-01T23:10:21.815+0000] {docker.py:438} INFO - [0m23:10:21  Schema silver criado/verificado
[2025-07-01T23:10:21.818+0000] {docker.py:438} INFO - [0m23:10:21  3 of 4 START hook: agronegocio_iceberg.on-run-start.2 .......................... [RUN]
[2025-07-01T23:10:21.819+0000] {docker.py:438} INFO - [0m23:10:21  3 of 4 OK hook: agronegocio_iceberg.on-run-start.2 ............................. [[32mOK[0m in 0.00s]
[2025-07-01T23:10:21.849+0000] {docker.py:438} INFO - [0m23:10:21  Schema gold criado/verificado
[2025-07-01T23:10:21.850+0000] {docker.py:438} INFO - [0m23:10:21  4 of 4 START hook: agronegocio_iceberg.on-run-start.3 .......................... [RUN]
[2025-07-01T23:10:21.851+0000] {docker.py:438} INFO - [0m23:10:21  4 of 4 OK hook: agronegocio_iceberg.on-run-start.3 ............................. [[32mOK[0m in 0.00s]
[2025-07-01T23:10:21.852+0000] {docker.py:438} INFO - [0m23:10:21
[2025-07-01T23:10:21.854+0000] {docker.py:438} INFO - [0m23:10:21  Concurrency: 2 threads (target='dev')
[2025-07-01T23:10:21.855+0000] {docker.py:438} INFO - [0m23:10:21
[2025-07-01T23:10:21.870+0000] {docker.py:438} INFO - [0m23:10:21  1 of 29 START test accepted_values_silver_dados_produtores_agro_trino_classificacao_propriedade__MINIFUNDIO__PEQUENA__MEDIA__GRANDE  [RUN]
[2025-07-01T23:10:21.870+0000] {docker.py:438} INFO - [0m23:10:21  2 of 29 START test accepted_values_silver_dados_produtores_agro_trino_cultura_principal__SOJA__MILHO__CAFE__CANA_DE_ACUCAR__ALGODAO__FRUTICULTURA__TRIGO__ARROZ__FEIJAO__EUCALIPTO  [RUN]
[2025-07-01T23:10:22.003+0000] {docker.py:438} INFO - [0m23:10:22  1 of 29 ERROR accepted_values_silver_dados_produtores_agro_trino_classificacao_propriedade__MINIFUNDIO__PEQUENA__MEDIA__GRANDE  [[31mERROR[0m in 0.13s]
[2025-07-01T23:10:22.007+0000] {docker.py:438} INFO - [0m23:10:22  3 of 29 START test accepted_values_silver_dados_produtores_agro_trino_faixa_risco_credito__SEM_SCORE__MUITO_ALTO__ALTO__MEDIO__BAIXO  [RUN]
[2025-07-01T23:10:22.101+0000] {docker.py:438} INFO - [0m23:10:22  3 of 29 ERROR accepted_values_silver_dados_produtores_agro_trino_faixa_risco_credito__SEM_SCORE__MUITO_ALTO__ALTO__MEDIO__BAIXO  [[31mERROR[0m in 0.09s]
[2025-07-01T23:10:22.105+0000] {docker.py:438} INFO - [0m23:10:22  4 of 29 START test accepted_values_silver_dados_produtores_agro_trino_finalidade_credito__CUSTEIO_SAFRA__INVESTIMENTO_MAQUINARIO__AMPLIACAO_AREA__OUTROS  [RUN]
[2025-07-01T23:10:22.667+0000] {docker.py:438} INFO - [0m23:10:22  2 of 29 PASS accepted_values_silver_dados_produtores_agro_trino_cultura_principal__SOJA__MILHO__CAFE__CANA_DE_ACUCAR__ALGODAO__FRUTICULTURA__TRIGO__ARROZ__FEIJAO__EUCALIPTO  [[32mPASS[0m in 0.79s]
[2025-07-01T23:10:22.683+0000] {docker.py:438} INFO - [0m23:10:22  5 of 29 START test accepted_values_silver_dados_produtores_agro_trino_registro_valido__True  [RUN]
[2025-07-01T23:10:22.865+0000] {docker.py:438} INFO - [0m23:10:22  5 of 29 ERROR accepted_values_silver_dados_produtores_agro_trino_registro_valido__True  [[31mERROR[0m in 0.17s]
[2025-07-01T23:10:22.874+0000] {docker.py:438} INFO - [0m23:10:22  6 of 29 START test accepted_values_silver_dados_produtores_agro_trino_tipo_pessoa__FISICA__JURIDICA  [RUN]
[2025-07-01T23:10:22.933+0000] {docker.py:438} INFO - [0m23:10:22  4 of 29 PASS accepted_values_silver_dados_produtores_agro_trino_finalidade_credito__CUSTEIO_SAFRA__INVESTIMENTO_MAQUINARIO__AMPLIACAO_AREA__OUTROS  [[32mPASS[0m in 0.83s]
[2025-07-01T23:10:22.941+0000] {docker.py:438} INFO - [0m23:10:22  7 of 29 START test dbt_utils_expression_is_true_silver_dados_produtores_agro_trino_area_total_hectares___0  [RUN]
[2025-07-01T23:10:23.637+0000] {docker.py:438} INFO - [0m23:10:23  6 of 29 PASS accepted_values_silver_dados_produtores_agro_trino_tipo_pessoa__FISICA__JURIDICA  [[32mPASS[0m in 0.76s]
[2025-07-01T23:10:23.641+0000] {docker.py:438} INFO - [0m23:10:23  8 of 29 START test dbt_utils_expression_is_true_silver_dados_produtores_agro_trino_localizacao_latitude__BETWEEN_90_AND_90  [RUN]
[2025-07-01T23:10:23.742+0000] {docker.py:438} INFO - [0m23:10:23  7 of 29 PASS dbt_utils_expression_is_true_silver_dados_produtores_agro_trino_area_total_hectares___0  [[32mPASS[0m in 0.80s]
[2025-07-01T23:10:23.748+0000] {docker.py:438} INFO - [0m23:10:23  9 of 29 START test dbt_utils_expression_is_true_silver_dados_produtores_agro_trino_localizacao_longitude__BETWEEN_180_AND_180  [RUN]
[2025-07-01T23:10:23.765+0000] {docker.py:438} INFO - [0m23:10:23  8 of 29 ERROR dbt_utils_expression_is_true_silver_dados_produtores_agro_trino_localizacao_latitude__BETWEEN_90_AND_90  [[31mERROR[0m in 0.12s]
[2025-07-01T23:10:23.848+0000] {docker.py:438} INFO - [0m23:10:23  10 of 29 START test dbt_utils_expression_is_true_silver_dados_produtores_agro_trino_valor_solicitado_credito___0  [RUN]
[2025-07-01T23:10:23.909+0000] {docker.py:438} INFO - [0m23:10:23  9 of 29 ERROR dbt_utils_expression_is_true_silver_dados_produtores_agro_trino_localizacao_longitude__BETWEEN_180_AND_180  [[31mERROR[0m in 0.16s]
[2025-07-01T23:10:23.915+0000] {docker.py:438} INFO - [0m23:10:23  11 of 29 START test dbt_utils_recency_silver_dados_produtores_agro_trino_hour__processed_at__24  [RUN]
[2025-07-01T23:10:24.023+0000] {docker.py:438} INFO - [0m23:10:24  11 of 29 ERROR dbt_utils_recency_silver_dados_produtores_agro_trino_hour__processed_at__24  [[31mERROR[0m in 0.10s]
[2025-07-01T23:10:24.027+0000] {docker.py:438} INFO - [0m23:10:24  12 of 29 START test dbt_utils_unique_combination_of_columns_silver_dados_produtores_agro_trino_proponente_id__data_solicitacao  [RUN]
[2025-07-01T23:10:24.608+0000] {docker.py:438} INFO - [0m23:10:24  10 of 29 PASS dbt_utils_expression_is_true_silver_dados_produtores_agro_trino_valor_solicitado_credito___0  [[32mPASS[0m in 0.76s]
[2025-07-01T23:10:24.610+0000] {docker.py:438} INFO - [0m23:10:24  13 of 29 START test not_null_silver_dados_produtores_agro_trino_area_total_hectares  [RUN]
[2025-07-01T23:10:25.041+0000] {docker.py:438} INFO - [0m23:10:25  12 of 29 FAIL 2 dbt_utils_unique_combination_of_columns_silver_dados_produtores_agro_trino_proponente_id__data_solicitacao  [[31mFAIL 2[0m in 1.01s]
[2025-07-01T23:10:25.056+0000] {docker.py:438} INFO - [0m23:10:25  14 of 29 START test not_null_silver_dados_produtores_agro_trino_classificacao_propriedade  [RUN]
[2025-07-01T23:10:25.222+0000] {docker.py:438} INFO - [0m23:10:25  14 of 29 ERROR not_null_silver_dados_produtores_agro_trino_classificacao_propriedade  [[31mERROR[0m in 0.16s]
[2025-07-01T23:10:25.225+0000] {docker.py:438} INFO - [0m23:10:25  15 of 29 START test not_null_silver_dados_produtores_agro_trino_cpf_cnpj ....... [RUN]
[2025-07-01T23:10:25.333+0000] {docker.py:438} INFO - [0m23:10:25  13 of 29 PASS not_null_silver_dados_produtores_agro_trino_area_total_hectares .. [[32mPASS[0m in 0.72s]
[2025-07-01T23:10:25.338+0000] {docker.py:438} INFO - [0m23:10:25  16 of 29 START test not_null_silver_dados_produtores_agro_trino_cultura_principal  [RUN]
[2025-07-01T23:10:25.872+0000] {docker.py:438} INFO - [0m23:10:25  15 of 29 PASS not_null_silver_dados_produtores_agro_trino_cpf_cnpj ............. [[32mPASS[0m in 0.65s]
[2025-07-01T23:10:25.882+0000] {docker.py:438} INFO - [0m23:10:25  17 of 29 START test not_null_silver_dados_produtores_agro_trino_data_solicitacao  [RUN]
[2025-07-01T23:10:25.950+0000] {docker.py:438} INFO - [0m23:10:25  16 of 29 PASS not_null_silver_dados_produtores_agro_trino_cultura_principal .... [[32mPASS[0m in 0.61s]
[2025-07-01T23:10:25.958+0000] {docker.py:438} INFO - [0m23:10:25  18 of 29 START test not_null_silver_dados_produtores_agro_trino_faixa_risco_credito  [RUN]
[2025-07-01T23:10:26.042+0000] {docker.py:438} INFO - [0m23:10:26  18 of 29 ERROR not_null_silver_dados_produtores_agro_trino_faixa_risco_credito . [[31mERROR[0m in 0.08s]
[2025-07-01T23:10:26.049+0000] {docker.py:438} INFO - [0m23:10:26  19 of 29 START test not_null_silver_dados_produtores_agro_trino_finalidade_credito  [RUN]
[2025-07-01T23:10:26.543+0000] {docker.py:438} INFO - [0m23:10:26  17 of 29 PASS not_null_silver_dados_produtores_agro_trino_data_solicitacao ..... [[32mPASS[0m in 0.66s]
[2025-07-01T23:10:26.546+0000] {docker.py:438} INFO - [0m23:10:26  20 of 29 START test not_null_silver_dados_produtores_agro_trino_localizacao_uf . [RUN]
[2025-07-01T23:10:26.639+0000] {docker.py:438} INFO - [0m23:10:26  20 of 29 ERROR not_null_silver_dados_produtores_agro_trino_localizacao_uf ...... [[31mERROR[0m in 0.09s]
[2025-07-01T23:10:26.641+0000] {docker.py:438} INFO - [0m23:10:26  21 of 29 START test not_null_silver_dados_produtores_agro_trino_processed_at ... [RUN]
[2025-07-01T23:10:26.696+0000] {docker.py:438} INFO - [0m23:10:26  19 of 29 PASS not_null_silver_dados_produtores_agro_trino_finalidade_credito ... [[32mPASS[0m in 0.64s]
[2025-07-01T23:10:26.707+0000] {docker.py:438} INFO - [0m23:10:26  22 of 29 START test not_null_silver_dados_produtores_agro_trino_proponente_id .. [RUN]
[2025-07-01T23:10:26.752+0000] {docker.py:438} INFO - [0m23:10:26  21 of 29 ERROR not_null_silver_dados_produtores_agro_trino_processed_at ........ [[31mERROR[0m in 0.11s]
[2025-07-01T23:10:26.761+0000] {docker.py:438} INFO - [0m23:10:26  23 of 29 START test not_null_silver_dados_produtores_agro_trino_registro_valido  [RUN]
[2025-07-01T23:10:26.902+0000] {docker.py:438} INFO - [0m23:10:26  23 of 29 ERROR not_null_silver_dados_produtores_agro_trino_registro_valido ..... [[31mERROR[0m in 0.14s]
[2025-07-01T23:10:26.907+0000] {docker.py:438} INFO - [0m23:10:26  24 of 29 START test not_null_silver_dados_produtores_agro_trino_row_hash ....... [RUN]
[2025-07-01T23:10:27.018+0000] {docker.py:438} INFO - [0m23:10:27  24 of 29 ERROR not_null_silver_dados_produtores_agro_trino_row_hash ............ [[31mERROR[0m in 0.11s]
[2025-07-01T23:10:27.026+0000] {docker.py:438} INFO - [0m23:10:27  25 of 29 START test not_null_silver_dados_produtores_agro_trino_tipo_pessoa .... [RUN]
[2025-07-01T23:10:27.536+0000] {docker.py:438} INFO - [0m23:10:27  22 of 29 PASS not_null_silver_dados_produtores_agro_trino_proponente_id ........ [[32mPASS[0m in 0.83s]
[2025-07-01T23:10:27.545+0000] {docker.py:438} INFO - [0m23:10:27  26 of 29 START test not_null_silver_dados_produtores_agro_trino_valor_solicitado_credito  [RUN]
[2025-07-01T23:10:27.902+0000] {docker.py:438} INFO - [0m23:10:27  25 of 29 PASS not_null_silver_dados_produtores_agro_trino_tipo_pessoa .......... [[32mPASS[0m in 0.87s]
[2025-07-01T23:10:27.906+0000] {docker.py:438} INFO - [0m23:10:27  27 of 29 START test source_not_null_bronze_dados_produtores_agro_proponente_id . [RUN]
[2025-07-01T23:10:28.598+0000] {docker.py:438} INFO - [0m23:10:28  26 of 29 PASS not_null_silver_dados_produtores_agro_trino_valor_solicitado_credito  [[32mPASS[0m in 1.04s]
[2025-07-01T23:10:28.601+0000] {docker.py:438} INFO - [0m23:10:28  28 of 29 START test test_incremental_integrity_trino ........................... [RUN]
[2025-07-01T23:10:28.757+0000] {docker.py:438} INFO - [0m23:10:28  28 of 29 ERROR test_incremental_integrity_trino ................................ [[31mERROR[0m in 0.15s]
[2025-07-01T23:10:28.761+0000] {docker.py:438} INFO - [0m23:10:28  29 of 29 START test unique_silver_dados_produtores_agro_trino_proponente_id .... [RUN]
[2025-07-01T23:10:28.899+0000] {docker.py:438} INFO - [0m23:10:28  27 of 29 PASS source_not_null_bronze_dados_produtores_agro_proponente_id ....... [[32mPASS[0m in 0.99s]
[2025-07-01T23:10:29.504+0000] {docker.py:438} INFO - [0m23:10:29  29 of 29 FAIL 2 unique_silver_dados_produtores_agro_trino_proponente_id ........ [[31mFAIL 2[0m in 0.74s]
[2025-07-01T23:10:29.510+0000] {docker.py:438} INFO - [0m23:10:29
[2025-07-01T23:10:29.511+0000] {docker.py:438} INFO - [0m23:10:29  Running 1 on-run-end hook
[2025-07-01T23:10:29.526+0000] {docker.py:438} INFO - [0m23:10:29  Execu√ß√£o finalizada
[2025-07-01T23:10:29.526+0000] {docker.py:438} INFO - [0m23:10:29  1 of 1 START hook: agronegocio_iceberg.on-run-end.0 ............................ [RUN]
[2025-07-01T23:10:29.527+0000] {docker.py:438} INFO - [0m23:10:29  1 of 1 OK hook: agronegocio_iceberg.on-run-end.0 ............................... [[32mOK[0m in 0.00s]
[2025-07-01T23:10:29.528+0000] {docker.py:438} INFO - [0m23:10:29
[2025-07-01T23:10:29.532+0000] {docker.py:438} INFO - [0m23:10:29
[2025-07-01T23:10:29.533+0000] {docker.py:438} INFO - [0m23:10:29  Finished running 29 tests, 5 hooks in 0 hours 0 minutes and 8.34 seconds (8.34s).
[2025-07-01T23:10:29.574+0000] {docker.py:438} INFO - [0m23:10:29
[2025-07-01T23:10:29.575+0000] {docker.py:438} INFO - [0m23:10:29  [31mCompleted with 15 errors and 0 warnings:[0m
[2025-07-01T23:10:29.577+0000] {docker.py:438} INFO - [0m23:10:29
[2025-07-01T23:10:29.578+0000] {docker.py:438} INFO - [0m23:10:29    Database Error in test accepted_values_silver_dados_produtores_agro_trino_classificacao_propriedade__MINIFUNDIO__PEQUENA__MEDIA__GRANDE (models/silver/schema.yml)
[2025-07-01T23:10:29.579+0000] {docker.py:438} INFO -   TrinoUserError(type=USER_ERROR, name=COLUMN_NOT_FOUND, message="line 18:9: Column 'classificacao_propriedade' cannot be resolved", query_id=20250701_231021_00263_ivifs)
[2025-07-01T23:10:29.580+0000] {docker.py:438} INFO - [0m23:10:29
[2025-07-01T23:10:29.582+0000] {docker.py:438} INFO - [0m23:10:29    Database Error in test accepted_values_silver_dados_produtores_agro_trino_faixa_risco_credito__SEM_SCORE__MUITO_ALTO__ALTO__MEDIO__BAIXO (models/silver/schema.yml)
[2025-07-01T23:10:29.583+0000] {docker.py:438} INFO -   TrinoUserError(type=USER_ERROR, name=COLUMN_NOT_FOUND, message="line 18:9: Column 'faixa_risco_credito' cannot be resolved", query_id=20250701_231022_00265_ivifs)
[2025-07-01T23:10:29.584+0000] {docker.py:438} INFO - [0m23:10:29
[2025-07-01T23:10:29.585+0000] {docker.py:438} INFO - [0m23:10:29    Database Error in test accepted_values_silver_dados_produtores_agro_trino_registro_valido__True (models/silver/schema.yml)
[2025-07-01T23:10:29.586+0000] {docker.py:438} INFO -   TrinoUserError(type=USER_ERROR, name=COLUMN_NOT_FOUND, message="line 18:9: Column 'registro_valido' cannot be resolved", query_id=20250701_231022_00271_ivifs)
[2025-07-01T23:10:29.587+0000] {docker.py:438} INFO - [0m23:10:29
[2025-07-01T23:10:29.589+0000] {docker.py:438} INFO - [0m23:10:29    Database Error in test dbt_utils_expression_is_true_silver_dados_produtores_agro_trino_localizacao_latitude__BETWEEN_90_AND_90 (models/silver/schema.yml)
[2025-07-01T23:10:29.590+0000] {docker.py:438} INFO -   TrinoUserError(type=USER_ERROR, name=COLUMN_NOT_FOUND, message="line 17:83: Column 'localizacao_latitude' cannot be resolved", query_id=20250701_231023_00278_ivifs)
[2025-07-01T23:10:29.591+0000] {docker.py:438} INFO - [0m23:10:29
[2025-07-01T23:10:29.592+0000] {docker.py:438} INFO - [0m23:10:29    Database Error in test dbt_utils_expression_is_true_silver_dados_produtores_agro_trino_localizacao_longitude__BETWEEN_180_AND_180 (models/silver/schema.yml)
[2025-07-01T23:10:29.593+0000] {docker.py:438} INFO -   TrinoUserError(type=USER_ERROR, name=COLUMN_NOT_FOUND, message="line 17:83: Column 'localizacao_longitude' cannot be resolved", query_id=20250701_231023_00279_ivifs)
[2025-07-01T23:10:29.594+0000] {docker.py:438} INFO - [0m23:10:29
[2025-07-01T23:10:29.595+0000] {docker.py:438} INFO - [0m23:10:29    Database Error in test dbt_utils_recency_silver_dados_produtores_agro_trino_hour__processed_at__24 (models/silver/schema.yml)
[2025-07-01T23:10:29.597+0000] {docker.py:438} INFO -   TrinoUserError(type=USER_ERROR, name=COLUMN_NOT_FOUND, message="line 24:13: Column 'processed_at' cannot be resolved", query_id=20250701_231023_00281_ivifs)
[2025-07-01T23:10:29.598+0000] {docker.py:438} INFO - [0m23:10:29
[2025-07-01T23:10:29.599+0000] {docker.py:438} INFO - [0m23:10:29  [31mFailure in test dbt_utils_unique_combination_of_columns_silver_dados_produtores_agro_trino_proponente_id__data_solicitacao (models/silver/schema.yml)[0m
[2025-07-01T23:10:29.600+0000] {docker.py:438} INFO - [0m23:10:29    Got 2 results, configured to fail if != 0
[2025-07-01T23:10:29.601+0000] {docker.py:438} INFO - [0m23:10:29
[2025-07-01T23:10:29.602+0000] {docker.py:438} INFO - [0m23:10:29    compiled Code at target/compiled/agronegocio_iceberg/models/silver/schema.yml/dbt_utils_unique_combination_o_21ab17eecd767bb91bd0b03d651fdd82.sql
[2025-07-01T23:10:29.603+0000] {docker.py:438} INFO - [0m23:10:29
[2025-07-01T23:10:29.604+0000] {docker.py:438} INFO - [0m23:10:29    See test failures:
[2025-07-01T23:10:29.605+0000] {docker.py:438} INFO -   ------------------------------------------------------------------------------------------------------------------
[2025-07-01T23:10:29.606+0000] {docker.py:438} INFO -   select * from "iceberg"."silver_dbt_test__audit"."dbt_utils_unique_combination_o_21ab17eecd767bb91bd0b03d651fdd82"
[2025-07-01T23:10:29.607+0000] {docker.py:438} INFO -   ------------------------------------------------------------------------------------------------------------------
[2025-07-01T23:10:29.608+0000] {docker.py:438} INFO - [0m23:10:29
[2025-07-01T23:10:29.609+0000] {docker.py:438} INFO - [0m23:10:29    Database Error in test not_null_silver_dados_produtores_agro_trino_classificacao_propriedade (models/silver/schema.yml)
[2025-07-01T23:10:29.610+0000] {docker.py:438} INFO -   TrinoUserError(type=USER_ERROR, name=COLUMN_NOT_FOUND, message="line 19:7: Column 'classificacao_propriedade' cannot be resolved", query_id=20250701_231025_00289_ivifs)
[2025-07-01T23:10:29.611+0000] {docker.py:438} INFO - [0m23:10:29
[2025-07-01T23:10:29.612+0000] {docker.py:438} INFO - [0m23:10:29    Database Error in test not_null_silver_dados_produtores_agro_trino_faixa_risco_credito (models/silver/schema.yml)
[2025-07-01T23:10:29.612+0000] {docker.py:438} INFO -   TrinoUserError(type=USER_ERROR, name=COLUMN_NOT_FOUND, message="line 19:7: Column 'faixa_risco_credito' cannot be resolved", query_id=20250701_231025_00298_ivifs)
[2025-07-01T23:10:29.613+0000] {docker.py:438} INFO - [0m23:10:29
[2025-07-01T23:10:29.614+0000] {docker.py:438} INFO - [0m23:10:29    Database Error in test not_null_silver_dados_produtores_agro_trino_localizacao_uf (models/silver/schema.yml)
[2025-07-01T23:10:29.615+0000] {docker.py:438} INFO -   TrinoUserError(type=USER_ERROR, name=COLUMN_NOT_FOUND, message="line 19:7: Column 'localizacao_uf' cannot be resolved", query_id=20250701_231026_00303_ivifs)
[2025-07-01T23:10:29.616+0000] {docker.py:438} INFO - [0m23:10:29
[2025-07-01T23:10:29.616+0000] {docker.py:438} INFO - [0m23:10:29    Database Error in test not_null_silver_dados_produtores_agro_trino_processed_at (models/silver/schema.yml)
[2025-07-01T23:10:29.617+0000] {docker.py:438} INFO -   TrinoUserError(type=USER_ERROR, name=COLUMN_NOT_FOUND, message="line 19:7: Column 'processed_at' cannot be resolved", query_id=20250701_231026_00305_ivifs)
[2025-07-01T23:10:29.618+0000] {docker.py:438} INFO - [0m23:10:29
[2025-07-01T23:10:29.619+0000] {docker.py:438} INFO - [0m23:10:29    Database Error in test not_null_silver_dados_produtores_agro_trino_registro_valido (models/silver/schema.yml)
[2025-07-01T23:10:29.626+0000] {docker.py:438} INFO -   TrinoUserError(type=USER_ERROR, name=COLUMN_NOT_FOUND, message="line 19:7: Column 'registro_valido' cannot be resolved", query_id=20250701_231026_00307_ivifs)
[2025-07-01T23:10:29.627+0000] {docker.py:438} INFO - [0m23:10:29
[2025-07-01T23:10:29.627+0000] {docker.py:438} INFO - [0m23:10:29    Database Error in test not_null_silver_dados_produtores_agro_trino_row_hash (models/silver/schema.yml)
[2025-07-01T23:10:29.628+0000] {docker.py:438} INFO -   TrinoUserError(type=USER_ERROR, name=COLUMN_NOT_FOUND, message="line 19:7: Column 'row_hash' cannot be resolved", query_id=20250701_231026_00309_ivifs)
[2025-07-01T23:10:29.629+0000] {docker.py:438} INFO - [0m23:10:29
[2025-07-01T23:10:29.630+0000] {docker.py:438} INFO - [0m23:10:29    Database Error in test test_incremental_integrity_trino (tests/singular/test_incremental_integrity_trino.sql)
[2025-07-01T23:10:29.630+0000] {docker.py:438} INFO -   TrinoUserError(type=USER_ERROR, name=COLUMN_NOT_FOUND, message="line 22:11: Column 'processed_at' cannot be resolved", query_id=20250701_231028_00319_ivifs)
[2025-07-01T23:10:29.631+0000] {docker.py:438} INFO - [0m23:10:29
[2025-07-01T23:10:29.632+0000] {docker.py:438} INFO - [0m23:10:29  [31mFailure in test unique_silver_dados_produtores_agro_trino_proponente_id (models/silver/schema.yml)[0m
[2025-07-01T23:10:29.633+0000] {docker.py:438} INFO - [0m23:10:29    Got 2 results, configured to fail if != 0
[2025-07-01T23:10:29.633+0000] {docker.py:438} INFO - [0m23:10:29
[2025-07-01T23:10:29.634+0000] {docker.py:438} INFO - [0m23:10:29    compiled Code at target/compiled/agronegocio_iceberg/models/silver/schema.yml/unique_silver_dados_produtores_agro_trino_proponente_id.sql
[2025-07-01T23:10:29.635+0000] {docker.py:438} INFO - [0m23:10:29
[2025-07-01T23:10:29.636+0000] {docker.py:438} INFO - [0m23:10:29    See test failures:
[2025-07-01T23:10:29.636+0000] {docker.py:438} INFO -   ----------------------------------------------------------------------------------------------------------
[2025-07-01T23:10:29.637+0000] {docker.py:438} INFO -   select * from "iceberg"."silver_dbt_test__audit"."unique_silver_dados_produtores_agro_trino_proponente_id"
[2025-07-01T23:10:29.638+0000] {docker.py:438} INFO -   ----------------------------------------------------------------------------------------------------------
[2025-07-01T23:10:29.638+0000] {docker.py:438} INFO - [0m23:10:29
[2025-07-01T23:10:29.639+0000] {docker.py:438} INFO - [0m23:10:29  Done. PASS=14 WARN=0 ERROR=15 SKIP=0 TOTAL=29
[2025-07-01T23:10:31.060+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-01T23:10:31.072+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 460, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 513, in execute
    return self._run_image()
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 384, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 446, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2025-07-01T23:10:31.078+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dbt_trino_silver_pipeline, task_id=dbt_test_silver, run_id=scheduled__2025-07-01T23:08:00+00:00, execution_date=20250701T230800, start_date=20250701T231013, end_date=20250701T231031
[2025-07-01T23:10:31.099+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 79 for task dbt_test_silver (Docker container failed: {'StatusCode': 1}; 734)
[2025-07-01T23:10:31.133+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-07-01T23:10:31.156+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-01T23:10:31.161+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
